server.port:9091

#Actuator property
#Enables all actuator end-points
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=*
#management.info.env.enabled = true

#To explicitly enable a specific end-point (e.g., /shutdown)
management.endpoint.shutdown.enabled=true

#To exclude something ie. /logger
management.endpoints.web.exposure.exclude=loggers

#To enable specific end points only
#management.endpoints.web.exposure.include=health,info,beans,env

#To get custom health detail, group wise, if authorized
management.endpoint.health.group.custom.show-components=when_authorized
management.endpoint.health.group.custom.show-details=when_authorized
management.endpoint.health.group.custom.include=diskSpace,ping
management.endpoint.health.group.custom.show-components=always
management.endpoint.health.group.custom.show-details=always


#Common Actuator End-points
#http://localhost:9091/actuator/health/custom
#http://localhost:9091/actuator/health
#http://localhost:9091/actuator/metrics/jvm.gc.pause
#http://localhost:9091/actuator/metrics/jvm.memory.max


